### PR TITLE
TEPHRA-162 Ensure TransactionVisibilityFilter cooperates with other filters

### PR DESCRIPTION
**Pull request by poornachandra**
JIRA - https://issues.cask.co/browse/TEPHRA-162

### CODE REVIEW

**Comment by gokulavasan** [comment]
Changes LGTM :+1:

**Comment by poornachandra** [comment]
Thanks @gokulavasan, I'll port the changes to other compat modules.

**Comment by poornachandra** [comment]
@gokulavasan I have ported the changes over to other compat modules. Please review.

**Comment by gokulavasan** [comment]
Finished review. Few comments. Rest LGTM :+1:

**Comment by poornachandra** [comment]
@gokulavasan Addressed comments. Will squash and merge.

**Comment by gokulavasan** [comment]
LGTM :+1:

**Pull request merged**
