### PR TITLE
TEPHRA-143 Treat Tephra delete markers from existing data as regular cells

### PR DESCRIPTION
**Pull request by poornachandra**
JIRA - https://issues.cask.co/browse/TEPHRA-143

Note: the changes are only in hbase-compat-0.98 for now.

### CODE REVIEW

**Comment by chtyim** [comment]
LGTM

**Comment by poornachandra** [comment]
Thanks Terence. I'll port to other compat modules.

**Comment by anwar6953** [comment]
Second commit LGTM.

**Comment by poornachandra** [comment]
Thanks Ali. Will squash and merge.

**Pull request merged**
