### PR TITLE
TEPHRA-174 Added support for HBase version 1.2.0-cdh5.7.0

### PR DESCRIPTION
**Pull request by sagarkapare**
JIRA: https://issues.cask.co/browse/TEPHRA-174

### CODE REVIEW

**Comment by sagarkapare** [comment]
@poornachandra Please take a look when you get a chance. Thanks!

**Comment by poornachandra** [comment]
@sagarkapare Changes look good. Can you update the README to include the CDH 5.6 and 5.7? Looks like we missed updating README for CDH 5.6.

**Comment by sagarkapare** [comment]
Thanks @poornachandra for review. Updated readme as well. Please take a look again.

**Comment by poornachandra** [comment]
LGTM

**Pull request merged**
