### PR TITLE
TEPHRA-156 Fix write to WAL by using durability API

### PR DESCRIPTION
**Pull request by poornachandra**
JIRA - https://issues.cask.co/browse/TEPHRA-156

### CODE REVIEW

**Comment by gokulavasan** [comment]
Code LGTM :+1: Wondering if its possible to add a unit test?

**Comment by poornachandra** [comment]
Good point about unit tests @gokulavasan, but it might be non-trivial to verify whether a Put got written into WAL in the tests. Let me look into this.

**Comment by poornachandra** [comment]
@gokulavasan Added tests, please take a look.

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by poornachandra** [comment]
Thanks @gokulavasan, will rebase and merge.

**Pull request merged**
