### PR TITLE
TEPHRA-94 Drop support for HBase 0.94

### PR DESCRIPTION
**Pull request by ghelmling**
Removes the HBase 0.94 compatibility module and the supporting docs.

### CODE REVIEW

**Comment by anew** [comment]
There is an HDFSUtil class that is a fork of an HBase 0.94 class. Perhaps it does not matter, but should that be updated, too?

**Comment by anew** [comment]
It seems that some of the methods in the compat modules can now be moved back to the core, because they are identical for .96 and .98

**Comment by ghelmling** [comment]
> There is an HDFSUtil class that is a fork of an HBase 0.94 class. Perhaps it does not matter, but should that be updated, too?

That is only used in the WAL recovery process, so it's not directly tied to the HBase 0.94 compatibility.  We could potentially replace that with use of the actual HBase class, but that will require plugging in to the compatibility layer.  I think it should be handled in a separate issue.

> It seems that some of the methods in the compat modules can now be moved back to the core, because they are identical for .96 and .98

It would be really nice to eliminate some of the code duplication between the modules, now that we don't have the KeyValue/Cell differences to deal with.  However, I think we should keep core clear of any HBase dependencies.  We could potentially have a parent hbase-compat module where common bits could go.  There is still no guarantee of binary compatibility, though, so this should still be compiled against the correct HBase version.  And there will be more client-side API changes coming in with HBase 1.0.  I think refining this structure will be an ongoing effort.

**Comment by anew** [comment]
Makes sense. LGTM

**Pull request merged**
