### PR TITLE
TEPHRA-172 Allow transaction sub-filters to see older cell versions

### PR DESCRIPTION
**Pull request by poornachandra**
JIRA - https://issues.cask.co/browse/TEPHRA-172

- [ ] Port unit test to other compat modules after review.

### CODE REVIEW

**Comment by chtyim** [comment]
LGTM

**Comment by poornachandra** [comment]
Thanks @chtyim. I'll port the test changes to other compat modules.

**Comment by sagarkapare** [comment]
@poornachandra Ported the test case to other modules and also made the ctor of `CellSkipFilter` and `TransactionVisibilityFilter` public. Please take a look. Thanks.

**Comment by poornachandra** [comment]
LGTM

**Comment by sagarkapare** [comment]
Build passed. Squashing and merging.

**Pull request merged**
